### ISSUE TITLE
Applivery unlocks landscape orientation

### ISSUE THREAD

**Issue by stantoncbradley** [applivery/applivery-android-sdk#19]
We lock portrait mode on android in our Android manifest
```
<activity
        android:name=".MainActivity"
        android:label="@string/app_name"
          android:screenOrientation="portrait"
          android:configChanges="keyboard|keyboardHidden|screenSize"
        android:windowSoftInputMode="adjustNothing">
```
however, when our testers use applivery to send feedback, landscape mode is enabled again? Any suggestions? thanks!

**Comment by CesarTrigo** [comment]
Hi again @stantoncbradley,
As in the previous issue, I just want to let you that we are looking into it. We0'll keep you updated.
Best,
C.

**Comment by stantoncbradley** [comment]
any update on this? we are still facing this issue.  thanks!
