### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by diegohdez90** [applivery/applivery-android-sdk#21]
It says there are three methods to install applivery but I see 5 methods. Please try to apply style to your README or add update subtitles in **SDK Installation** section.

Also, add table of contents.

**Comment by CesarTrigo** [comment]
HI @diegohdez90 and thank you for the comments
As you will see, we've just released a new update that includes:
* TOC
* More clarity on the SDK Installation methods section
* ther minor styling improvements

Thank you,
C.
