### ISSUE TITLE
Unable to update App - Download progress at 0%

### ISSUE THREAD

**Issue by CesarTrigo** [applivery/applivery-android-sdk#22]
While updating the App though Force Update or Automatic Update, the download progress sticks to 0%. It happens in multiple devices reported below, except in Nokia 6.1 where the installation button (only in Force Update) does not work at all and the view seems to be duplicated everytime the user clicks on it.

<img width="1008" alt="report" src="https://user-images.githubusercontent.com/453657/46467241-8a75d000-c7cd-11e8-9aa4-063610ff96b2.png">

(Private video available)

**Comment by DavidUps** [comment]
the problem with the Nokia mobile 6.1 happens with the Automatic Updates

**Comment by CesarTrigo** [comment]
Thank you for the clarification @DavidUps.

In the meantime, the team has discovered in the provided video that both Apps (and therefore, both devices) don't have any permissions granted. Applivery needs the Internal Storage Write permissions to be able to download the new version that will be installed (apk file).
The question has been raised to the client.

**Comment by CesarTrigo** [comment]
A hotfix version has been deployed to prevent identification errors when rare (not common) Android devices attempt to install a new version of the App. 3 new topics are under investigation:
- Sometimes **Force Update** does not launch installation after download finishes
- Sometimes **Automatic Update** process does not launch installation after download finishes

**Devices:** One Plus 3T and One Plus 5 
**OS:** Android 8.0.0 and 8.1

**Comment by CesarTrigo** [comment]
Our team has detected that Google Play Protect might be blocking App installation from the Update message. Apparently, there's a workaround to request installation by adding the following permission `REQUEST_INSTALL_PACKAGES ` as described here: https://developer.android.com/reference/android/Manifest.permission#REQUEST_INSTALL_PACKAGES

**Comment by CesarTrigo** [comment]
It's confirmed that the issue is fixed based on previous message. New version 2.6.1 will be deployed soon.

**Comment by CesarTrigo** [comment]
Released: https://github.com/applivery/applivery-android-sdk/releases/tag/v2.6.1
