### ISSUE TITLE
Error message dialogs displayed to end-users

### ISSUE THREAD

**Issue by CesarTrigo** [applivery/applivery-android-sdk#24]
Some Android users are being prompted with error dialogs when the SDK receives connectivity errors from the API.

As described by the client:
> Android Applivery is showing error message dialogs to the end users (for example if network Connection is not working, and the app cannot connect to the applivery-dashboard). These dialogs do only have one clickable button: Aceptar (in Spanish).

Tentative corrective actions:
- Disable error dialogs
- Move all error messages to the logging system

**Comment by CesarTrigo** [comment]
Reported again by another customer in Oct 25th 2018

**Comment by mrebollob** [comment]
Fixed in https://github.com/applivery/applivery-android-sdk/commit/0b14612161d490220cdfbdc09bd814109f0fa20d
