### ISSUE TITLE
El botón aparece al bloquear y desbloquear.

### ISSUE THREAD

**Issue by DavidUps** [applivery/applivery-android-sdk#27]
Hola, soy david de servicio mantenimiento Repsol.
Tenemos la versión v2.6.1 y pasa en la Samsung Galaxy  Active 2
Lo que ocurre es que cuando forzamos la actualización de la aplicación, el botón solo se muestra cuando se bloquea y desbloquea la aplicación.

**Comment by CesarTrigo** [comment]
Hola @DavidUps, gracias por escribirnos.
Por confirmar, ¿con "botón" te refieres al diálogo de actualización que te permite atualizar o postponer la actualización?

Muchas gracias,
C.

**Comment by CesarTrigo** [comment]
Duplicate of #28
