### ISSUE TITLE
Do not display Update or Force update dialogs when coming from background

### ISSUE THREAD

**Issue by CesarTrigo** [applivery/applivery-android-sdk#28]

**Comment by CesarTrigo** [comment]
A new method `Applivery.checkForUpdatesBackground()` will be included to optionally enable checking for updates when coming from Background

**Comment by mrebollob** [comment]
Done in https://github.com/applivery/applivery-android-sdk/commit/cee9b3a7cbe56635cfaa9d78c9b892b00608461d
