### ISSUE TITLE
No aparece el botón de actualizar

### ISSUE THREAD

**Issue by DavidUps** [applivery/applivery-android-sdk#29]
Buenos días.

En las tablet, cuando forzamos actualización, no aparece el botón de actualización.
Lo hemos podido probar en android 7,5

![screenshot_20181119-182157](https://user-images.githubusercontent.com/22979841/48724528-b4723d00-ec29-11e8-8077-78fb875ac160.jpg)

**Comment by DavidUps** [comment]
También hay veces que el método   

> AppliverySdk.isAppLocked()

no funciona correctamente, ya que esta en true y no bloquea la pantalla

**Comment by CesarTrigo** [comment]
Bug identified! Working on a permanent fix.
Tentative release date **Dec 3rd**.

**Comment by CesarTrigo** [comment]
Update: tentative release Nov 28 as a hotfix

**Comment by mrebollob** [comment]
Fixed in v2.6.3. Release commit: 6d07229effbbd7cc95c20845ab6a6a4735548782
