### ISSUE TITLE
Imposibilidad de actualizar aplicación. Crash. Api 7 y 8 de Android.

### ISSUE THREAD

**Issue by movilidadSoporte** [applivery/applivery-android-sdk#30]
Forzamos la instalación obligatoria. Justo tras completarse la descarga de la aplicación más actualizada a través de applivery, se produce un crash.  La aplicación no se actualiza. Al volver a abrir la aplicación, inmediatamente se produce el crash.  Sólamente afecta a versiones de Android 7 y 8, no a inferiores.
Puede que esté relacionada con los permisos sobre el acceso a ficheros.
La traza completa es la siguiente:

AndroidAppInstallerImpl.java line 73
com.applivery.applvsdklib.tools.androidimplementations.AndroidAppInstallerImpl.composeUri

Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{com.repsol.nace.ssoo/com.karumi.dexter.DexterActivity}: java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/emulated/0/Download/Servicios oficiales PRO_5c597c349a9a1b5b46fe5686.apk
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2804)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2875)
android.app.ActivityThread.-wrap12 (ActivityThread.java)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1578)
android.os.Handler.dispatchMessage (Handler.java:105)
android.os.Looper.loop (Looper.java:156)
android.app.ActivityThread.main (ActivityThread.java:6623)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:942)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:832)

Caused by java.lang.IllegalArgumentException
Failed to find configured root that contains /storage/emulated/0/Download/Servicios oficiales PRO_5c597c349a9a1b5b46fe5686.apk
android.support.v4.content.FileProvider$SimplePathStrategy.getUriForFile (FileProvider.java:678)
android.support.v4.content.FileProvider.getUriForFile (FileProvider.java:377)
com.applivery.applvsdklib.tools.androidimplementations.AndroidAppInstallerImpl.composeUri (AndroidAppInstallerImpl.java:73)
com.applivery.applvsdklib.tools.androidimplementations.AndroidAppInstallerImpl.install (AndroidAppInstallerImpl.java:48)
com.applivery.applvsdklib.tools.androidimplementations.AndroidAppInstallerImpl.onPathReady (AndroidAppInstallerImpl.java:65)
com.applivery.applvsdklib.tools.androidimplementations.AndroidExternalStorageReaderImpl.checkPath (AndroidExternalStorageReaderImpl.java:64)
com.applivery.applvsdklib.tools.androidimplementations.AndroidExternalStorageReaderImpl.access$000 (AndroidExternalStorageReaderImpl.java:32)
com.applivery.applvsdklib.tools.androidimplementations.AndroidExternalStorageReaderImpl$1.onPermissionAllowed (AndroidExternalStorageReaderImpl.java:72)
com.applivery.applvsdklib.tools.permissions.AbstractPermissionListener.onPermissionGranted (AbstractPermissionListener.java:48)
com.karumi.dexter.listener.single.CompositePermissionListener.onPermissionGranted (CompositePermissionListener.java:54)
com.karumi.dexter.MultiplePermissionsListenerToPermissionListenerAdapter.onPermissionsChecked (MultiplePermissionsListenerToPermissionListenerAdapter.java:48)
com.karumi.dexter.MultiplePermissionListenerThreadDecorator$1.run (MultiplePermissionListenerThreadDecorator.java:45)
com.karumi.dexter.MainThread.execute (MainThread.java:32)
com.karumi.dexter.MultiplePermissionListenerThreadDecorator.onPermissionsChecked (MultiplePermissionListenerThreadDecorator.java:43)
com.karumi.dexter.DexterInstance.onPermissionsChecked (DexterInstance.java:264)
com.karumi.dexter.DexterInstance.updatePermissionsAsGranted (DexterInstance.java:238)
com.karumi.dexter.DexterInstance.onActivityReady (DexterInstance.java:133)
com.karumi.dexter.Dexter.onActivityReady (Dexter.java:162)
com.karumi.dexter.DexterActivity.onCreate (DexterActivity.java:31)

**Comment by CesarTrigo** [comment]
Hola @movilidadSoporte ,
Gracias por el reporte. Vamos a verificar con prioridad qué puede estar pasando.

**Comment by CesarTrigo** [comment]
Buenos días,
Se ha lanzado la [v2.6.5](https://github.com/applivery/applivery-android-sdk/releases/tag/v2.6.5) que modifica el comportamiento del `FileProvider` para prevenir la incompatibilidad detectada con vuestra App.

**Comment by CesarTrigo** [comment]
Se reabre la incidencia tras confirmación por parte de @movilidadSoporte de que el problema persiste con versiones 8 y 9 de Android. Se solicita acceso al binario por email para realizar nuevas pruebas.

**Comment by CesarTrigo** [comment]
Se reabre la incidencia tras confirmación por parte de @movilidadSoporte de que el problema persiste con versiones 8 y 9 de Android. Se solicita acceso al binario por email para realizar nuevas pruebas.
