### ISSUE TITLE
Release Build Crashes - Proguard Rules missing

### ISSUE THREAD

**Issue by fentino** [applivery/applivery-android-sdk#32]
Can you please provide some Proguard rules?

The SDK crashes when Proguard is enabled.

I tried
`-keep class com.applivery.applvsdklib.** { *; }`
which helps.
But it would be nice if you could provide more specific rules.

**Comment by fentino** [comment]
Since 3.0.10 you also have to add:
`-keep class com.applivery.updates.data.response.** { *; }`
`-keep class com.applivery.base.data.ServerResponse { *; }`

**Comment by maxlapides** [comment]
@CesarTrigo Is there any progress on this issue? We are adding these Proguard rules to our build as a workaround for now. Thanks!

**Comment by CesarTrigo** [comment]
Hi @maxlapides actually yes. The issue was selected for development in our last Sprint Planning. We forgot to update it here accordingly. We hope to have it ready in the next few days.
I will keep you posted.
C.

**Comment by CesarTrigo** [comment]
Hi @maxlapides @fentino, apologies for the wait and thank you for your patience.

We have just released [v3.4](https://github.com/applivery/applivery-android-sdk/releases/tag/v3.4) of the SDK that includes some fixes for this issue. Can you please give it a try and let us know if you continue facing any problems?

Thank you.
C.
