### ISSUE TITLE
Corrupted apk file after download error

### ISSUE THREAD

**Issue by llDavidll** [applivery/applivery-android-sdk#44]
Hi,

I found that when a download error occurs, then the update cannot be done (even after launching the app again). Here is what I think happens :

The download of the update package sometimes get stuck when you have a poor connection (I have waited a long time at 90% for example, then killed the app).
The only way of exiting the app when it's stuck is to kill it, but then a temporary apk file is present in the download folder. If you relaunch the app and click "Update", it will not try to re-download the file. Since the file is not complete it will not install correctly. I think a quick fix would be to always delete this file if it exists when the user clicks "Update", to force a new download. If this file is already there, there was probably a download error so it's no a valid file.

It's easy to reproduce :
- Make the app start to download the update package
- Turn off your connection (it will try to install an invalid file)
- Re-open the app. The update popup will be displayed, and when you click "Update" it will not redownload the file. I think it should delete the file, then download it again.
You can also test by creating an empty file, then giving it the exact same name as the update package (including extension) and copying it in the download folder.

**Comment by CesarTrigo** [comment]
Released in [v3.0.3](https://github.com/applivery/applivery-android-sdk/releases/tag/3.0.3)
