### ISSUE TITLE
Update package download location

### ISSUE THREAD

**Issue by llDavidll** [applivery/applivery-android-sdk#45]
Hi,

I saw that you download the update packages in the public download folder. This is not a problem for me right now, but if someone targets Android 10 (29) and does not set `android:requestLegacyExternalStorage="true"` in its manifest, this will crash on Android 10 devices. Would it be possible to use internal cache folder of the app instead ? It would have multiple benefits :
- Does not crash on Android 10 without requestLegacyExternalStorage
- Ready for Android 11
- No need to ask for the external storage permission
- The cache folder can be cleaned by the system if space is needed

Programmatically speaking, it means replacing
`Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)`
by
`context.getCacheDir()`

You need to have access to a context, but I think this change is necessary : all user may not want to use requestLegacyExternalStorage, and this is just a temporary solution, as told in the red warning here https://developer.android.com/training/data-storage/files/external-scoped#opt-out-of-scoped-storage

**Comment by CesarTrigo** [comment]
Released in [v3.0.3](https://github.com/applivery/applivery-android-sdk/releases/tag/3.0.3)
