### ISSUE TITLE
Publication of v3.0.4

### ISSUE THREAD

**Issue by llDavidll** [applivery/applivery-android-sdk#47]
Hi,

Thanks for publishing this new version, but I'm having issues retrieving it.

I have jCenter() and mavenCentral() in my gradle repositories. If I add
`implementation 'com.applivery:applivery-sdk:3.0.4'`
It does not found the lib on jcenter. I tried with `:v3.0.4`, it does not work either.

I also tried using https://jitpack.io and 
`'com.github.Applivery:applivery-android-sdk:v3.0.4'`
This time it finds the main artifact, but fails to retrieve transitive dependencies (applivery-base).

I also tried version 3.0.3 with the same result.

For me, version 3.0.1 was working thanks to mavenCentral, but the new version is not available on it :
https://search.maven.org/search?q=g:com.applivery

**Comment by CesarTrigo** [comment]
Hi @llDavidll ,

Thank you for opening the issue. After some quick checks, you can find the v3.0.4 has been successfully published and verified in [Bintray](https://bintray.com/applivery/maven/applivery-android-sdk/3.0.4) that supports both Maven and Gradle.

Jitpack also has green light for v3.0.4: https://jitpack.io/#Applivery/applivery-android-sdk/v3.0.4

May I ask you to check again and come back to us with the result?

However, we will be publishing today another minor version solving a couple of additional issues so you might want to wait for it.

Thank you,
C.

**Comment by llDavidll** [comment]
Ok sorry about jitpack, I had an issue in my gradle config file. 
I'm using group filters for jitpack repository, and I didn't notice they were two differents ones for AppLivery (`com.github.Applivery` for the main artifact, `com.github.Applivery.applivery-android-sdk` for others). It's working fine now.

Still, I think there is an issue with the first (and easiest) way of implementing your sdk in the readme :

"Gradle with jCenter dependency"
`implementation 'com.applivery:applivery-sdk:3.0.4'`

I have jCenter() declared as a repository, and it does not find the app livery sdk :

> ERROR: Failed to resolve: com.applivery:applivery-sdk:3.0.4

The exact same configuration with `com.applivery:applvsdklib:3.0.1` works fine.

**Comment by llDavidll** [comment]
The sdk is working better than before, but the notification you use during the download is pretty annoying : it makes the photo vibrate / ring continuously. It seems like unwanted behavior :)

I don't want to create a new issue now since you told me a new version in on the way.

I think the notification can make a noise when it's opened for the first time (but it should be an option in the sdk, quiet / not quiet download notification). But it sure should not make the photo ring on each progress update.

**Comment by CesarTrigo** [comment]
Released in [v3.0.5](https://github.com/applivery/applivery-android-sdk/releases/tag/v3.0.5)
