### ISSUE TITLE
 Showing Dialog with Title Applivery Exception 

### ISSUE THREAD

**Issue by vnd-ranga** [applivery/applivery-android-sdk#50]
![image](https://user-images.githubusercontent.com/15669922/68586644-1f57fc00-04ab-11ea-918d-d946c0408988.png)

We suspects It opens a dialogue everytime there is an exception. We are monitoring the crashes and we dont want the appliverly dialogue to come everytime there is no internet or an unhandled exception

**Comment by vnd-ranga** [comment]
you can generate by init SDK without internet

**Comment by CesarTrigo** [comment]
Fixed in [v3.1.0](https://github.com/applivery/applivery-android-sdk/releases/tag/v3.1.0)
