### ISSUE TITLE
Feedback & Bug reporting not working [BUG]

### ISSUE THREAD

**Issue by itaiterner** [applivery/applivery-android-sdk#53]
**Account information**
Organization Owner email address: it@elegantmonkeys.com
App ID: Better

**Describe the bug**
1. There is no edit text component for writing the issue.
2. the attached screen showing black screen.
3. The "send" button not working

**To Reproduce**
Shake the phone to open the Feedback & Bug reporting screen

**Expected behavior**
1. Write some text
2. Capture the actual screen
3. Send the report

**Screenshots**
![Screenshot_20191226-144546](https://user-images.githubusercontent.com/7588919/71476723-26369600-27ef-11ea-9ef8-c1edc3fabade.jpg)

**Smartphone (please complete the following information):**
 - Device:Samsung Galaxy s8 
 - OS: Android 9

**Additional context**
- App develop using flutter.
- The Applivery installed on the native side.

**Comment by CesarTrigo** [comment]
Fixed and released
