### ISSUE TITLE
Download limit control

### ISSUE THREAD

**Issue by CesarTrigo** [applivery/applivery-android-sdk#54]
Log a warning message when the API returns a `5003` code.
Message: `Installations limit exceeded. Limit: X / month`

Sample API Response:
```
{
    "status":false,
    "error":{
        "code":5003,
        "message":"Limit Exceeded",
        "data": {
             "itemName":"downloads",
              "limit":6000,"num":7838
        }
    }
}
```

@Jaimeer , please confirm that the correct code is `5003`.

**Comment by mrebollob** [comment]
Implemented in 702990728d3f9e43f93f038c7f8ce9f3f0a7ab1e
