### ISSUE TITLE
[BUG] Control the exception for Object Expected

### ISSUE THREAD

**Issue by Beni84** [applivery/applivery-android-sdk#56]
**Account information**
Organization Owner email address: Gigigo
App ID: McDonalds :-D

**Describe the bug**
The application crashed yesterday afternoon and it was because the response of the request that arrived was not a string instead of an object as expected. It would be necessary to control the exception of the request library for when the object cannot be parsed to have a controllable generic error.

**To Reproduce**

**Expected behavior**
Fatal Exception: com.google.gson.JsonSyntaxExceptionjava.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $ Raw Text
--
  | com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read + 226 (ReflectiveTypeAdapterFactory.java:226)
  | com.google.gson.Gson.fromJson + 927 (Gson.java:927)
  | com.google.gson.Gson.fromJson + 892 (Gson.java:892)
  | com.google.gson.Gson.fromJson + 841 (Gson.java:841)
  | com.google.gson.Gson.fromJson + 813 (Gson.java:813)
  | com.applivery.applvsdklib.network.api.model.ErrorDataEntityResponse$Companion.parseError + 37 (AppliveryErrorEntity.kt:37)
  | com.applivery.applvsdklib.network.api.requests.ServerRequest.performRequest + 53 (ServerRequest.java:53)
  | com.applivery.applvsdklib.network.api.requests.ObtainAppConfigRequest.performRequest + 41 (ObtainAppConfigRequest.java:41)
  | com.applivery.applvsdklib.network.api.requests.ServerRequest.execute + 31 (ServerRequest.java:31)
  | com.applivery.applvsdklib.domain.appconfig.ObtainAppConfigInteractor.performRequest + 63 (ObtainAppConfigInteractor.java:63)
  | com.applivery.applvsdklib.domain.BaseInteractor.run + 54 (BaseInteractor.java:54)
  | java.util.concurrent.ThreadPoolExecutor.runWorker + 1133 (ThreadPoolExecutor.java:1133)
  | java.util.concurrent.ThreadPoolExecutor$Worker.run + 607 (ThreadPoolExecutor.java:607)
  | java.lang.Thread.run + 776 (Thread.java:776)

**Comment by CesarTrigo** [comment]
Thank you again @Beni84!
Actually the error was triggered yesterday because of a server side incident causing an error when accessing the API. As you have just described, that situation must be controlled from the `SDK` in case the `JSON` response is not properly formed and/or the actual service is not working.

**Comment by mrebollob** [comment]
Fixed the JsonSyntaxException in 1e9b6ffaae69f0a90ccb5c4bc6bc6ef3221abf79
