### ISSUE TITLE
 [BUG] Screenshot feedback not working on when targeting Android 10+

### ISSUE THREAD

**Issue by imablanco** [applivery/applivery-android-sdk#58]
**Account information**
Organization Owner email address: alvaro.bl91@gmail.com
App ID:

**Describe the bug**
According to Android documentation (https://developer.android.com/training/data-storage#scoped-storage), when targeting API 29+ apps are given scoped storage by default, meaning that they are only allowed to access files within their app-specific directory. In this case the SDK is trying to access screenshots directory that is outside the app scope so the feature is no longer working.

**To Reproduce**
1. Go to Sample App
2. Enable screenshot feedback
3. Take a screenshot
4. Nothing happens

**Smartphone (please complete the following information):**
 - Device: Pixel 2XL
 - OS: Android 10

**Additional context**
Working on a PR for this.

**Comment by CesarTrigo** [comment]
Fixed and released in [v3.1.1](https://github.com/applivery/applivery-android-sdk/releases/tag/v3.1.1).
Thank you for the contribution :raised_hands:
