### ISSUE TITLE
Remove support for isStoreRelease

### ISSUE THREAD

**Issue by CesarTrigo** [applivery/applivery-android-sdk#64]
**Is your feature request related to a problem? Please describe.**
Some companies are reporting issues while uploading Apps to Google Play with the Applivery SDK integrated (even when it's disabled using the `isStoreRelease=true`)

**Describe the solution you'd like**
We will be removing support for `isStoreRelease` feature.
We will highly recommend conditionally exclude the Applivery SDK for builds that will be published  in the Google Play Store.

**Comment by mrebollob** [comment]
Done in 83cc29fe675bd512c37a531666b3b2b7a9b56100
